### ISSUE TITLE
Making a public post results in `-v`

### ISSUE THREAD

**Issue by atsaloli** [tigillo/linkedin-cli#4]
Hi. I just tried to post something:

```
$ linkedin post -v public "My team at Spokeo is interviewing for a Senior DevOps Engineer. Let me know if there is anyone I should talk to."
INFO: Post sent!
$
```

I went to LinkedIn and saw I posted `-v`.  That was the entire content of the post.

**Comment by maaydin** [comment]
@atsaloli must be fine with 0.1.4 but tbh I couldn't get a chance to test it. Please let me know any issues.
https://pypi.org/project/linkedin-cli/0.1.4/

**Comment by atsaloli** [comment]
@maaydin thanks! works beautifully with 0.1.4.  Nicely done!
