### ISSUE TITLE
Is there any way to have LinkedIn post to Twitter via `linkedin-cli`?

### ISSUE THREAD

**Issue by atsaloli** [tigillo/linkedin-cli#5]
Hi! Thanks for a great useful tool. 

When I go to LinkedIn in the Web browser, it lets me post simultaneously to LinkedIn and Twitter.

Is there any way to do that using `linkedin-cli`?

**Comment by maaydin** [comment]
Linkedin api has a feature for it called `distribution` but it's not supported with linkedin-cli yet.

https://docs.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api?tabs=http#distribution

**Comment by atsaloli** [comment]
Understood, thank you @maaydin !
